services:
    navi:
        build:
            context: .
            dockerfile: Dockerfile
        image: navi:latest
        container_name: navi-container
        restart: always
        depends_on:
            - mariadb
        env_file:
            - .env
        volumes:
            - .:/app
        networks:
            - bot-network
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'

    mariadb:
        image: mariadb:latest
        container_name: mariadb-container
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - bot-network
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'

volumes:
    db_data:

networks:
    bot-network:
